# Generated by Django 4.2.4 on 2023-08-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menu_date_created'),
        ('order', '0003_alter_cart_user_alter_category_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='menu',
            field=models.ManyToManyField(to='menu.menu'),
        ),
    ]
