# Generated by Django 4.2.4 on 2023-08-28 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_cart_category_remove_cart_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='menu',
        ),
    ]
