# Generated by Django 4.2.4 on 2023-08-28 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_category_remove_order_price_order_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.RESTRICT, to='order.cart'),
            preserve_default=False,
        ),
    ]
